language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      apt_packages: libapparmor-dev
    - os: linux
      dist: trusty
      sudo: required
      apt_packages: libapparmor-dev
      env: R_CODECOV=true

r_binary_packages:
  - devtools

r_github_packages:
  - jimhester/covr

r_check_args: "--as-cran --run-dontrun"

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: XjCNOufVyfFUl9MIW6Vh7d/lcInse0lM3Le/XAdOJLYMpqwGiVQjhbxcHU68uXSX2LmuraLA0PsXTq6Hw2ciNUFo5oqCdTkhTNRbk8S5mzZWupZzGR1JEdAtP3MlOQcRmeObzw35pEdJh4fmG7OPhq4vLCeh915oClmFYyoXBgk=

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
